version: "3.9"
services:
  pg_client:
      environment:
        PGDATABASE: ${pg_database}
        PGHOST: ${pg_host}
        PGPORT: ${pg_port}
        PGUSER: ${pg_user}
        PGPASSWORD: ${pg_password}
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: ${pg_database}
      POSTGRES_USER: ${pg_user}
      POSTGRES_PASSWORD: ${pg_password}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${pg_user} -d ${pg_database}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
